base_model: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
jsonl_path: "./data/data_100.jsonl"
adapter_name: "dev_support_colora"
output_dir: "./colora_output"
device: "mps"

lambda_orth: 0.01
lambda_collab: 0.001
orthogonalize_freq: 30

training_args:
  per_device_train_batch_size: 16
  num_train_epochs: 10
  learning_rate: 3e-4
  max_grad_norm: 1.0
  logging_steps: 20
  save_steps: 500
  output_dir: "./colora_output/dev_support_colora"
  remove_unused_columns: false
  report_to: "none"
